name = "erpbot-banker"

compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

route = { pattern = "erpbot.app/banker/*", zone_name = "erpbot.app" }


[dev]
port = 8082

[[services]]
binding = "Users"
service = "erpbot-statesman"
entrypoint = "Users"

