name = "erpbot-statesman"

workers_dev = false

compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8081

[[services]]
binding = "Users"
service = "erpbot-statesman"
entrypoint = "Users"

[[services]]
binding = "Shipments"
service = "erpbot-statesman"
entrypoint = "Shipments"

# [durable_objects]
# bindings = [{name = "Users", class_name = "Users"}]

# [[migrations]]
# tag = "v1" # Should be unique for each entry
# new_classes = ["Users"]