name = "randobot-sheriff"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

route = { pattern = "sipbot.app/*", zone_name = "sipbot.app" }

[dev]
port = 8080

[[services]]
binding = "Users"
service = "randobot-statesman"
entrypoint = "Users"

[vars]
REDIRECT_DOMAIN = "sipbot.app"
DISCORD_REDIRECT_URI="https://sipbot.app/auth/callback"