name = "randobot-sheriff"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[dev]
port = 8080

[[services]]
binding = "STATESMAN"
service = "randobot-statesman"
entrypoint = "Statesman"

[vars]
REDIRECT_DOMAIN = "randobot.app"
DISCORD_REDIRECT_URI="https://randobot.app/auth/callback"