name = "erpbot-dropship"

compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

route = { pattern = "erpbot.app/dropship/*", zone_name = "erpbot.app" }

[dev]
port = 8089

[[services]]
binding = "Users"
service = "erpbot-statesman"
entrypoint = "Users"

[[services]]
binding = "Shipments"
service = "erpbot-statesman"
entrypoint = "Shipments"

[[services]]
binding = "Addresses"
service = "erpbot-statesman"
entrypoint = "Addresses"